#! /bin/bash

set -e pipefail

source prereqs.lib

prereqs.init 'The drake vendor source distribution prerequisites script'

prereqs.assert_sudo

if prereqs.tag_applies "drake|all"; then
    prereqs.apt install python3-requests
    SCRIPT_DIR=$(dirname $0)
	if prereqs.interactive; then
	    ${SCRIPT_DIR}/drake_installer --interactive
	else
	    ${SCRIPT_DIR}/drake_installer
	fi
	if [ $? -ne 0 ]; then
	    prereqs.die "drake_installer failed"
    fi
fi

prereqs.done
