#! /bin/bash

set -e pipefail

source prereqs.lib

prereqs.init 'The drake vendor source distribution prerequisites script'

prereqs.assert_sudo

if prereqs.tag_applies "drake|all"; then
    prereqs.apt install python3-requests
	if prereqs.interactive; then
	    PATH=".":${PATH} drake-installer --interactive
	else
	    PATH=".":${PATH} drake-installer
	fi
	if [ $? -ne 0 ]; then
	    prereqs.die "drake-installer failed"
    fi
fi

prereqs.done
